export const CREATE_RATING_REQUEST = "CREATE_RATING_REQUEST";
export const CREATE_RATING_SUCCESS = "CREATE_RATING_SUCCESS";
export const CREATE_RATING_FAILURE = "CREATE_RATING_FAILURE";

export const GET_RATINGS_REQUEST = "GET_RATINGS_REQUEST";
export const GET_RATINGS_SUCCESS = "GET_RATINGS_SUCCESS";
export const GET_RATINGS_FAILURE = "GET_RATINGS_FAILURE";
